SELECT
    DISTINCT [ROLE],
    U.NAME,
    LNAME_REP,
    SFDC_OWNER AS REP_EMAIL
FROM
    qryDE_FACTO_ASSIGNMENTS D
    LEFT JOIN sfdcUser U ON D.SFDC_OWNER = U.EMAIL
    INNER JOIN qryRoster R ON D.SFDC_OWNER = R.REP_EMAIL
    AND [isLATEST?] = 1
ORDER BY
    LNAME_REP